# Generated by Django 2.0.6 on 2018-12-16 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_auto_20181215_1327'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='student',
            order_with_respect_to='exam_grade',
        ),
    ]
